# Generated by Django 2.2 on 2019-12-21 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20191218_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_image',
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('assignemnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_images', to='classroom.Assignment')),
            ],
        ),
    ]
